config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  resources :users, only: [:index, :create, :new]
  resources :users, only: [:show, :edit, :update, :destroy, :add_hoby], param: :search_id
  resource :rooms

  root 'home#index'
  get 'home/show'
  post 'home/reject'
  post 'home/create_room'

  post 'rooms/report_user'
  post 'rooms/end_chat'

  get 'users/show'
  post 'users/add_hoby'
  post 'users/delete_hoby'
  post 'users/chat_request'
  get 'users/index'
  get 'users/show'
  post 'users/delete_icon'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates_uniqueness_of :search_id
  has_many :user_hoby, foreign_key: :user_id, dependent: :destroy
  has_many :hoby, through: :user_hoby, dependent: :destroy
  has_many :report
  has_many :messages, foreign_key: :user_id, dependent: :destroy

  mount_uploader :icon, IconUploader

  def to_param
    search_id
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  protected
    def after_update_path_for(resource)
      user_path(resource)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only:[:add_hoby, :delete_hoby, :chat_request]
  before_action :correct_user, only: :delete_hoby

  # キーワードによるユーザー検索結果
  def index
    @users = []
    if Hoby.find_by(hoby_name: params[:keyword])
      hoby_id = Hoby.find_by!(hoby_name: params[:keyword]).id
      UserHoby.where(hoby_id: hoby_id).where.not(user_id: current_user.id).each do |get_user_hoby|
        @users.push(User.find(get_user_hoby["user_id"]))
      end
    end
  end

  # ユーザーのプロフィールページ
  def show
    @user = User.find_by!(search_id: params[:search_id])
  end

  # 趣味を新たに追加する
  def add_hoby
    @add_hoby = params[:hoby_name]
    if @add_hoby != ""
      # 同じ名前の趣味がまだ登録されていないときのみ登録
      my_hobies = current_user.hoby.pluck(:hoby_name)
      if my_hobies.exclude?(@add_hoby)
        current_user.user_hoby.build(hoby: Hoby.find_or_create_by(hoby_name: @add_hoby))
        if current_user.save
          redirect_to user_path(current_user.search_id)
        end
      else
        redirect_to user_path(current_user.search_id)
      end
    end
  end

  # 登録している趣味を中間テーブルから削除する
  def delete_hoby
    @delete_hoby = params[:id]
    @my_hoby = current_user.user_hoby.find_by(hoby_id: @delete_hoby)
    if @my_hoby.delete
      redirect_to user_path(current_user.search_id)
    end
  end

  # アイコンを削除する
  def delete_icon
    s3 = AWS::S3.new
    folder = "uploads/user/icon/#{current_user.id}"
    bucket = s3.buckets['chatapp-myicon']
    bucket.objects.each do |object|
      object.delete
    end
    redirect_to user_path(current_user.search_id)
  end

  # チャット申請する
  def chat_request
    original_user = User.find(current_user.id)
    dest_user = User.find_by!(search_id: params[:dest_search_id])
    original_user_id = current_user.id.to_i

    # チャット申請可能の場合
    if dest_user.chat_request == 0
      dest_user.chat_request = original_user_id
      original_user.chat_request = -2
    end

    if dest_user.save and original_user.save
      redirect_to root_path
    end
  end

  private
    def hoby_params
      params.require(:hoby).permit(:hoby_name)
    end

    def correct_user
      @hoby = current_user.hoby.find_by(id: params[:id])
      redirect_to root_url if @hoby.nil?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div style="text-align: center;">
  <h1>検索結果 <%= @users.length %>件</h1>
  <br>
  <% @users.each do |user| %>
    <div id="search_user_box">
      <div id="search_user_icon">
        <% if user.icon.to_s != "" %>
          <%= image_tag user.icon.to_s, id:"my_search_icon" %>
        <% else %>
            <%= image_tag "/image/person.png", id:"my_search_icon" %>
          <% end %>
      </div>
      <div id="search_user_name"><%= link_to user.name, user %></div>
      <div id="search_user_profile"><%= user.introduction %></div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<% if user_signed_in? %>
  <div id="my_page_content">
    <% if @user.icon.to_s != "" %>
      <%= image_tag @user.icon.to_s, class:"my_icon"%>
    <% else %>
      <%= image_tag "/image/person.png", class:"my_icon"%>
    <% end %>
    <div id="my_name"><%= @user.name %></div>
    <% if current_user.search_id != @user.search_id and @user.chat_request != -2 %>
      <%= link_to "チャットを申請", users_chat_request_path(dest_search_id: params[:search_id]),
                  method: :post, id: "chat_request" %>
    <% end %>

    <div id="chat_count">チャットカウント : <%= @user.chat_count %></div>
    <div id="my_introduction"><%= @user.introduction %></div>

    <% if current_user.search_id == @user.search_id %>
      <div id="input_hoby_box">
        <%= form_tag users_add_hoby_path, method: :post do %>
          <input name="hoby_name" value="" class="input_hoby_name" autocomplete="off" placeholder="キーワード">
          <input type="submit" value="追加" class="hoby_submit_btn">
        <% end %>
      </div>
    <% end %>

    <div class="hoby_area">
      <% @user.user_hoby.each do |my_hoby| %>
        <div id="hoby"><%= my_hoby.hoby.hoby_name %></div>
          <% if @user == current_user %>
            <%= link_to "☓", users_delete_hoby_path(id: my_hoby.hoby.id), method: :post %>
          <% end %>
        <br>
      <% end %>
    </div>
  </div>
<% end %>