config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  resources :users, only: [:index, :create, :new]
  resources :users, only: [:show, :edit, :update, :destroy, :add_hoby], param: :search_id
  resource :rooms

  root 'home#index'
  get 'home/show'
  post 'home/reject'
  post 'home/create_room'

  post 'rooms/report_user'
  post 'rooms/end_chat'

  get 'users/show'
  post 'users/add_hoby'
  post 'users/delete_hoby'
  post 'users/chat_request'
  get 'users/index'
  get 'users/show'
  post 'users/delete_icon'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
#  チャット申請・断るときの遷移 chat_requestの初期値は0
#  DestUser(申請先) : OriginUserのID　  → 0 (NG)
#                                     → -1 (OK)
#  OriginalUser(申請元) : -2           →　-4 (NG)  → 0
#                                     → -1  (OK)

  def index
    if user_signed_in?
      # もしチャット申請がきている場合画面に表示させる
      @announce = ""
      @chat_status = 0
      chat_request = User.find(current_user.id).chat_request

      if chat_request != 0

        if chat_request != -2 and chat_request != -4 and chat_request != -1 # チャット申請が送られてきた
          @announce = "さんからチャット申請！"
          @chat_status = 1
          @origin_user = User.find(chat_request)

        elsif chat_request == -4 # チャット申請が断られた
          @announce = "チャット申請が断られました。"
          @chat_status = 2
          current_user.chat_request = 0
          current_user.save

        elsif chat_request == -1    # チャットルームへ移動
          chatroom_id = current_user.chat_room
          @announce = chatroom_id
          @chat_status = 3
          redirect_to rooms_path()
        end

      else
        @announce = ""
        @chat_status = 0
      end

    end
  end

  # チャット申請を断る
  def reject
    @origin_user = User.find(params[:origin_id])
    current_user.chat_request = 0
    @origin_user.chat_request = -4
    current_user.save!
    @origin_user.save!
  end

  # チャット申請を許諾する
  def create_room
    @room = Room.create!
    @origin_user = User.find(params[:origin_id])

    current_user.chat_room = @room.id
    @origin_user.chat_room = @room.id

    current_user.chat_request = -1
    @origin_user.chat_request = -1

    current_user.save!
    @origin_user.save!
    redirect_to root_path
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div id="top_content">
  <% if user_signed_in? %>
    <div class="logined_top_title">
      Concierge
    </div>
    <% if @chat_status != 0 %>
      <% if @chat_status == 1 %>    <!-- チャット申請あり -->
        <div id="cloud">
          <div id="cloud_message">
            <%= link_to @origin_user.name, user_path(@origin_user.search_id) %><%= @announce %><br>
            <%= link_to "承認", home_create_room_path(origin_id: @origin_user.id), method: :post %>
            <%= link_to "断る", home_reject_path(origin_id: @origin_user.id), method: :post %>
          </div>
        </div>

      <% elsif @chat_status == 2 %>　　<!-- チャット申請が断られた -->
        <%= @announce %>

      <% elsif @chat_status == 3 %>  <!-- チャット申請を受け付けた -->
        <%= @announce %>
      <% end %>
    <% else %>
      <!-- ユーザー検索フォーム -->
      <div class="search">
        <%= form_tag(users_path, :method => 'get', :class => 'sform') do %>
          <%= text_field_tag :keyword, '', placeholder: 'キーワード', class:'sbox', autocomplete: 'off' %>
          <%= submit_tag 'Search', :name => nil, :class => 'sbtn'%>
        <% end %>
      </div>
    <% end %>

  <% else %>
    <div class="top_title">
      Concierge
    </div>
    <div class="top_detail">
      Concierge(コンシェルジュ) は会話をサポートしてくれるチャットアプリです.
    </div>
  <% end %>
</div>

app/views/home/show.html.erb
<h1>Home#show</h1>
<p>Find me in app/views/home/show.html.erb</p>