config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  resources :users, only: [:index, :create, :new]
  resources :users, only: [:show, :edit, :update, :destroy, :add_hoby], param: :search_id
  resource :rooms

  root 'home#index'
  get 'home/show'
  post 'home/reject'
  post 'home/create_room'

  post 'rooms/report_user'
  post 'rooms/end_chat'

  get 'users/show'
  post 'users/add_hoby'
  post 'users/delete_hoby'
  post 'users/chat_request'
  get 'users/index'
  get 'users/show'
  post 'users/delete_icon'
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def show
    if current_user.chat_room != -1
      @room = Room.find(current_user.chat_room)
      @messages = @room.messages
      @target_user = User.where(chat_room: @room.id).where.not(id: current_user.id).first
    else
      redirect_to root_path
    end
  end

  # チャットを終了する
  def end_chat
    end_change_user
    redirect_to root_path
  end

  # ユーザーを通報する
  def report_user
    Report.create!({user_id: current_user.id, target_id: params[:target_id]})
    @reported_user_count = Report.where(target_id: params[:target_id]).count

    end_change_user
    if @reported_user_count >= 2
      User.find(params[:target_id]).destroy
    end
    redirect_to root_path
  end

  private

  # chat_requestとchat_roomをデフォルト値に変更
  def end_change_user
    @target_user = User.where(chat_room: current_user.chat_room).where.not(id: current_user.id).first
    @target_user.chat_request = 0
    @target_user.chat_room = -1
    current_user.chat_request = 0
    current_user.chat_room = -1

    current_user.increment!(:chat_count, 1)
    @target_user.increment!(:chat_count, 1)

    current_user.save!
    @target_user.save!
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/show.html.erb
<div style="text-align: center;">
  <h2><%= link_to @target_user.name, @target_user %>さんとのチャットルーム</h2>
  <!-- 表示の左右わけに使う閲覧ユーザー情報 -->
  <div id="show_user" data-show_user="<%= current_user.id %>"></div>

  <div id="messages">
    <%= render @messages %>
  </div>
  <div id="make_question_now"></div>
  <div id="load_mark"></div>
  <br>

  <div id="on_input_status"></div>
  <%= text_field nil, nil, 'data-behavior': 'room_speaker', id:'message_input_box', autocomplete: 'off' %>
  <br>

  <div id="end_chat">
    <%= link_to "チャットを終了", rooms_end_chat_path(), method: :post, data:
        { confirm: 'チャットを終了しますか?',
          cancel: 'やめる',
          commit: '終了する'}, title: '終了確認' %>
  </div>
  <div id="report_user">
    <%= link_to "ユーザーを通報", rooms_report_user_path(target_id: @target_user.id), method: :post, data:
        { confirm: 'ユーザーを通報しますか？',
          cancel: 'やめる',
          commit: '通報する'}, title: '通報確認' %>
  </div>
</div>